[package]
name = "wasm4"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasm4-sys = { path = "../wasm4-sys" }
